### ISSUE TITLE
404 on http://127.0.0.1:4000/js/jquery/jquery.min.js

### ISSUE THREAD

**Issue by hussra** [josephdadams/midi-relay#14]
I'm trying out midi-relay 2.2.0 on Windows 64-bit. Downloaded and unzipped midi-relay2.2.0-win-x64.zip, and I'm finding that on the settings page (http://127.0.0.1:4000/settings) not a whole lot is working (e.g. no MIDI ports listed, though I know loopMIDI is installed and working - it's listed in the midi-relay console window).

Peering into the Chrome dev tools, it looks like it's trying to pull in http://127.0.0.1:4000/js/jquery/jquery.min.js and getting a 404 error back.

It looks like http://127.0.0.1:4000/js/jquery/jquery.js is present and correct, but not the minified version that the settings page is asking for.

**Comment by josephdadams** [comment]
Just saw this. I missed the notification. Sorry about that. It is probably an issue with the way I packaged the binaries. I will look into building new releases that fix this problem.

**Comment by hussra** [comment]
No problem. I was able to figure out how to configure what I needed in midi-triggers.json, but just thought I'd report this while it was fresh in my mind.
