### ISSUE TITLE
Help with sending commands?

### ISSUE THREAD

**Issue by MixDatSalt** [josephdadams/midi-relay#17]
I'm really new to this so any help is greatly appreciated! 

How come this isn't working?

`http://127.0.0.1:4000/sendmidi/midiport=StreamDeck2Daw&midicommand=cc&channel=1&controller=2&value=1`

returns with

 `{"error":true,"url":"/sendmidi/midiport=StreamDeck2Daw&midicommand=cc&channel=1&controller=2&value=1 not found."}`

I know everything should be working because I can use the Bitfocus companion module and it works perfectly.

The end goal is to send HTTP Get and Post Midi commands from Touch Portal.

Edit: Never mind, finally figured it out after hours of testing lmao

**Comment by YDeltagon** [comment]
Hello, 
I just liked to use a midi keyboard (APC MINI) with Midi-Relay and TouchPortal, like that, instead of launching the live twitch from my phone, I can do it from my midi keyboard, the same for the soundboard, you would have a idea?
