### ISSUE TITLE
Basic SetUp - (MAC)

### ISSUE THREAD

**Issue by scaryxpuppy** [josephdadams/midi-relay#2]
Hi there,

Forgive my new-ness, as I am certainly not a programmer at all,

But am looking at trying to install and run the MIDI-RELAY program on my Mac and then use with companion.

Have seen the descriptions Tech Ministry and looks like a great solution to a couple of my workarounds.

Any advice or help in installing and running or if there's an "instruction manual" would be greatly appreciated.

Best regards

PHIL

**Comment by josephdadams** [comment]
I totally missed seeing this. I’m sorry. In the future, please follow up in a few days if I haven’t responded! Let me know if you still need assistance.
