### ISSUE TITLE
Feature Request: support more GET requests

### ISSUE THREAD

**Issue by mark-epstein** [josephdadams/midi-relay#20]
Sorry I don't know all the right terminology.  

Instead of requiring this in a POST
```
 {
 midiport: 'MIDI Port Name',
 midicommand: 'noteon',
 channel: 0, 
 note: 21,
 velocity: 1
 }
```
How about also accepting a GET with parameters, such as this:
`http://127.0.0.1/sendmidi?midiport="MIDI Port Name&midicommand=noteon&channel=0&note=21&velocity=1`

**Comment by josephdadams** [comment]
Your terminology is fine. I added this feature in December 2019. It's in the documentation.

**Comment by mark-epstein** [comment]
Thanks! I'll concede I missed that the Readme says, 

> You can also make an HTTP GET request with the parameters passed as querystrings.

but in my defense the descriptive paragraph at the top only mentions POST requests: 

> midi-relay is designed to allow you to send an HTTP POST request, with JSON data in the body

**Comment by josephdadams** [comment]
Feel free to make a PR to make the description more helpful :)
