### ISSUE TITLE
midi-relay Feedback in Companion?

### ISSUE THREAD

**Issue by StockwerkOrange** [josephdadams/midi-relay#22]
Hi,
i'm using a Roland V-1HD Videomixer and control them over midi-relay on a RPi with Companion. It would be nice to have Feedback in Companion for (Tally) get Information about input 1-4 on A or B, FX A or B is on/off and so on. Maybe you can help me with this?

kind regards

[V-1HD_RC_guide_eng02_W.pdf](https://github.com/josephdadams/midi-relay/files/6328161/V-1HD_RC_guide_eng02_W.pdf)

**Comment by josephdadams** [comment]
midi generally does not return feedback and midi relay does not process any return data.
