### ISSUE TITLE
2.1 and 2.2 release not working on Windows 10

### ISSUE THREAD

**Issue by nivinm** [josephdadams/midi-relay#26]
Hello, 

I tried running midi-relay 2.1 and 2.2 on two PC's using rtpmidi on both machines or bome network on both machines. Machine 1 was using ProPresenter 7 7.4.2 and machine 2 only had Companion running. The goal was to send a cue from Pro7 to companion to press certain buttons. 

Each time I ran midi-relay (2.1 or 2.2) it would not see the cues coming from Pro7. I ran the settings page and everything was blank, even though the console said it was able to load the input and output midi ports. 

Troubleshooting

1. I could use midi view on the Companion PC and I could see the midi coming over from Pro7 PC
2. I went the reverse (turned off midi-relay on Companion PC, turned on midi-relay on Pro7 PC) sent a midi cue from Companion PC to the Pro7 PC and it was able to read the midi cue. 
3. I used the midi-relay API to query for midi inputs/outputs - found everything 
4. I tried adding a trigger through the api and it said invalid midi port (even though the last api found it)

Solution
I ran midi-relay 2.0 on the Companion machine and (yay) worked perfectly.

**Comment by josephdadams** [comment]
Did you run it from source at any point, or just the binaries?

**Comment by nivinm** [comment]
I did, but ran into various missing module requests. After I installed one it would complain about the next, after the third one I figured there are a lot of modules that are missing :). Is there a way to run a script of required modules and then install? 

Error: Cannot find module 'request'
Error: Cannot find module 'express'
Error: Cannot find module 'body-parser'

**Comment by nivinm** [comment]
Oh you know what, I just ran npm install inside of the source directory and it took care of all the missing modules. Then ran node main.js and it worked!

**Comment by josephdadams** [comment]
Great!

**Comment by agbrint** [comment]
Can confirm, released binaries 2.2.0 for Windows do not pick up any of the MIDI devices on my machine nor other hosts.  Multiple machines tested.  Suggest reopen or re-release?  I have not tried source yet.

**Comment by josephdadams** [comment]
Try from source as it’s likely a packaging issue with the binaries.
