### ISSUE TITLE
[Feature Request] Adding MIDI program change commands.

### ISSUE THREAD

**Issue by Fader-Monkey** [josephdadams/midi-relay#3]
It would be great to have the ability to trigger MIDI program change commands. In general it would be great to have all the different MIDI channel voice messages. In my case adding Program change commands would open up some control of audio consoles such as the DiGiCo SD series. I unfortunately do not have the skills to add the feature myself but I would be more than happy to help test, or help in any way I can.

**Comment by josephdadams** [comment]
I am working to add other MIDI message types in the 2.0 release which will be available soon!

**Comment by josephdadams** [comment]
@Fader-Monkey program change commands and all the different MIDI channel voice messages are now implemented in 2.0. Go check it out! :)
