### ISSUE TITLE
SysEx Message fails always

### ISSUE THREAD

**Issue by airbenich** [josephdadams/midi-relay#33]
I'm trying to send an SysEx Message like this:
`f0 43 10 3E 11 01 00 42 00 26 00 2F 00 00 00 00 00 F7`

Unfortunately i get the following output:
````
Sending SysEx MIDI Message to Port: USB MIDI Interface
Not a valid SysEx message.
[ 'F0', '43 10 3E 11 01 00 42 00 26 00 2F 00 00 00 00 00 F7' ]
````
It looks like there is a bug in the if statement (& else) in line 980.
When my input value `messageArray[0]` equals `F0`, then Line 980 will be true and Line 982 will lead to `NaN`.
Therefore line 987 will be true and the execution stops.
Or do i miss a thing here?

https://github.com/josephdadams/midi-relay/blob/4cfd6610f40f0853fb78e048359e16c0be6e5103/main.js#L979-L992

**Comment by phrankdachicken** [comment]
Does "0xF0,0x41,0x10,0x00,0x00,0x00,0x68,0x12,0x00,0x12,0x01,0x00,0x6D,0xF7" work instead of "F0, 41 10 00 00 00 68 12 00 12 01 00 6D F7"?

**Comment by josephdadams** [comment]
please try the latest release and if not fixed, re-open this issue
