### ISSUE TITLE
Unhandled error when opening midirelay

### ISSUE THREAD

**Issue by DVEntertainment** [josephdadams/midi-relay#38]
I've installed midirelay on my new windows 11 machine after using it for the past year on my win10 machine. But when i try to run it here, it gives me an unhandled error (see screenshot) What should i do?

this is the error
![image](https://user-images.githubusercontent.com/65161300/236701641-0a78c7a2-9e87-4e08-887b-0d160d80f627.png)

thanx!

**Comment by josephdadams** [comment]
fixed in 3.0.2
