### ISSUE TITLE
Feature Request:  Rotate Volume

### ISSUE THREAD

**Issue by houtacheng** [josephdadams/midi-relay#40]
Rotate right(+1) or left(-1) to adjust the fader level.
<img width="541" alt="image" src="https://github.com/josephdadams/midi-relay/assets/25832189/a6399e74-b368-4f03-8dcb-7ada3ad68e0e">

**Comment by josephdadams** [comment]
All the fields support custom variables now. So just create a volume variable, increment or decrement it with the rotation action, and then send the midi action referencing that variable. Maybe delay it slightly to give companion time to update the variable value.

**Comment by josephdadams** [comment]
To do it your way would require knowing the current value, which is not possible given that MIDI is one-way or at the very least custom response based.
