### ISSUE TITLE
Feature Request: Add the inbound midi triggers into version 3+.

### ISSUE THREAD

**Issue by mwb9aa** [josephdadams/midi-relay#42]
Thank you for all of your work updating midi-relay.

My church extensively uses the inbound midi triggers provided by midi-relay versions prior to 3 to navigate through an Ableton Live set, control camera preset positions, stage and house lights, and video input switching on an ATEM Mini Pro all using Bitfocus Companion as the software bringing all those things together.

Ableton plays a midi note-->loopMIDI (virtual version of RTPmidi)-->midi-relay-->Bitfocus Companion-->Action

Please consider adding inbound midi triggers into the current version.

**Comment by hussra** [comment]
Like @mwb9aa, our church makes extensive use of inbound midi triggers to midi-relay. In our case, it is from Proclaim lighting signals, to loopMIDI, to midi relay, to Companion, to controlling our Atem Mini video switchers.

What would be needed to make this happen in midi-relay 3.x?

**Comment by josephdadams** [comment]
If you can throw some money at it, I can find some time. My email is on my github profile. Otherwise the features between midi relay 2.x and 3.x are currently the same. One is just easier to launch depending on your OS.

**Comment by josephdadams** [comment]
Added in v3.1.0
