### ISSUE TITLE
Feature Request: Remove automatic "All Notes Off" for every channel

### ISSUE THREAD

**Issue by jsjoen7896** [josephdadams/midi-relay#44]
Hello! I am trying to send MIDI notes to a DAW using a stream deck pedal, and it wasn't working until I realized (using a MIDI monitor) that every "Note On" / "Note Off" message that I send is accompanied automatically by a "All Notes Off" signal for all channels 1-16.

It would be nice to implement for a future release to have a checkbox in the setup screen to not have the "All Note Off" messages to send on every action. I know that the module is optimized for lighting control, and the note off messages are a nice blanket MIDI reset, but it would be super nice to be able to create music using the MIDI Relay module for Companion!

Thanks for the amazing work!
Josh

**Comment by josephdadams** [comment]
fixed in 3.1.1, thanks for figuring this one out, @jsjoen7896
