### ISSUE TITLE
fail to get v2.0.1 to run; node main.js throws exception, after (maybe) fix, can't see MIDI device

### ISSUE THREAD

**Issue by mark-epstein** [josephdadams/midi-relay#45]
**Describe the bug**
```
levpres@CompanionPi:~/source/midi-relay-2.0.1 $ node main.js
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /home/levpres/source/midi-relay-2.0.1/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/levpres/source/midi-relay-2.0.1/main.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/levpres/source/midi-relay-2.0.1/main.js' ]
}

Node.js v20.6.0
```

**To Reproduce**
installed mid-relay v2.0.1
also occurred on 2.0

I got midi-relay to run by running `npm install request` but I have no idea if that's right. midi-relay seems to be running but won't recognize my MIDI hardware
![image](https://github.com/josephdadams/midi-relay/assets/80222240/1354e3d5-d017-4d3a-81ec-753f91c90881)

os: Debian GNU/Linux 11 (bullseye)
Raspberry Pi 4 Model B Rev 1.4

**Comment by mark-epstein** [comment]
Also, Companion doesn't seem to connect to midi-relay. The log shows this if I stop and start the connection, but the Connections page never advances past "Connecting

**Comment by mark-epstein** [comment]
sorry last comment of the night. Same Pi, same USB-MIDI hardware, works fine with an older SD card that has Companion v2.3.1 on it. I don't know how to determine the midi-relay version, I lost the SSH credentials.
![image](https://github.com/josephdadams/midi-relay/assets/80222240/85dcf102-d6c4-484e-a34a-79cf3becc48a)

**Comment by mark-epstein** [comment]
Maybe this info is useful

![image](https://github.com/josephdadams/midi-relay/assets/80222240/e5449816-ae7c-42e3-82a1-143201a0c8f9)

![image](https://github.com/josephdadams/midi-relay/assets/80222240/16c0b51a-ad7f-40c7-b36e-58a1b3f7aa05)

**Comment by mark-epstein** [comment]
OK, I just saw this.
![image](https://github.com/josephdadams/midi-relay/assets/80222240/fcc5d3f3-e408-4bd5-831c-2f7a4648b892)
If I can't run midi-relay at all with Companion v3 that will make me very sad. I have invested tons of time researching and planning a move to v3.
But the option to select lower (2.x) protocol versions confuses me if this is the case; I'm hoping the "only compatible with midi-relay v3.0 or greater" is incorrect?

**Comment by josephdadams** [comment]
At some point if I can find the time (or if someone hires me to find the time) I will make the current midi-relay v3.x codebase be able to run on a Pi. And eventually I will deprecate and remove the v2.x functionality within the companion module entirely.

Unless you particularly need this to run on a Pi, just download midi-relay v3.x and run it on a desktop computer with that USB midi interface.
