### ISSUE TITLE
Unable to open script interfaces v3.1.2 in macOS Sonoma

### ISSUE THREAD

**Issue by eakwarren** [josephdadams/midi-relay#48]
Hi @josephdadams

First, thank you for creating midi-relay.

**Describe the bug**
Midi-relay AppleScript and Shell Script options not available in 3.1.2. I unpacked the .asar file and edited static/intex.html and script.js to show them and repacked. However, scripts don't seem to run.  Is something larger not working that prompted their removal?

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version 14.1.1

**Comment by josephdadams** [comment]
It’s probably crashing for some reason. Also midi relay 3  no longer executes AppleScripts.
