### ISSUE TITLE
Sending Sysex using Midi Relay

### ISSUE THREAD

**Issue by WITELITE2020** [josephdadams/midi-relay#52]
Joseph -  Your program is great and is a big help with Midi on Companion. THANK YOU!!

I am able to send PC and CC messages without issue and have used a Midi Monitor to confirm they are sending.

However, when I go to send Sysex messages, nothing happens and the Midi Monitor shows nothing being transmitted.

I've confirmed the Sysex string works using another program to transmit it so I know that's not the issue. 

Any idea what else it could be?

Thanks

MM

**Comment by josephdadams** [comment]
How are you sending them?

**Comment by WITELITE2020** [comment]
I figured it out. If you send decimals separated by commas it works.  I was using hex separated by spaces but that didn’t work.  Something like the below did

240, 65, 16, 0, 0, 0, 32, 18, 112, 1, 18, 0, 0, 15, 110, 247

Thanks

MM
