### ISSUE TITLE
midi-relay does not take into consideration grid size

### ISSUE THREAD

**Issue by patrickraths** [josephdadams/midi-relay#62]
I have just installed midi-relay (windows) and I'm able to send midi notes from ProPresenter to Companion as expected. 

However, the issue I am facing is that midi-relay doesn't seem to correctly adapt my configured grid size. I have configured a grid size of 12 buttons x 10 rows, i.e. a grid size of 11 by 9
<img width="572" alt="image" src="https://github.com/user-attachments/assets/56b325cd-d1c7-4ef3-89da-ed3db745bf56">

This is the configuration of midi-relay. Based on my understand sending MIDI note1 0 should trigger button 1/0/0, while Midi note 1 would trigger button 1/0/1, etc.
<img width="590" alt="image" src="https://github.com/user-attachments/assets/96d16303-c036-4a89-9bf0-6fe7fabf57f4">

This works fine up until sending MIDI Note 7 i.e. this correctly triggers button 1/0/7. However, when sending MIDI Note instead of triggering button 1/0/8 button 1/1/0 is being trigger.

During my attempts to troubleshoot this issue I discovered the following in the comanion config file export:
It seems like midi-relay is still assuming a 8 by 4 grid size. I tried to change the values and uploaded the config again but it still triggers the wrong button i.e. 1/1/0 instead of 1/0/8.
<img width="472" alt="image" src="https://github.com/user-attachments/assets/c5344b83-af72-47a7-8014-28d4b88258dd">

Any thoughts how this could be fixed?

**Comment by josephdadams** [comment]
This is not a midi relay issue but with the companion module for it. Please post it there: https://github.com/bitfocus/companion-module-techministry-midirelay

**Comment by patrickraths** [comment]
Sorry, just saw this. Will doPatrick Raths 華樂善On 31 Jul 2024, at 11:10, Joseph Adams ***@***.***> wrote:﻿
This is not a midi relay issue but with the companion module for it. Please post it there: https://github.com/bitfocus/companion-module-techministry-midirelay
